### ISSUE TITLE
regarding "Add IPv6 support #195" -- another exception, shoud check also hasattr

### ISSUE THREAD

**Issue by shula** [webpy/webpy#308]
current git code:

    try:
        socket.inet_pton(socket.AF_INET6, address)
    except socket.error:
        return False

i get this error:

  File "C:\python\lib\site-packages\web\net.py", line 33, in validip6addr
    socket.inet_pton(socket.AF_INET6, address)
AttributeError: 'module' object has no attribute 'inet_pton'

I suggest:

    def validip6addr(address):
        (...)
        if not hasattr(socket, 'inet_pton'):
            return False
        try:
            socket.inet_pton(socket.AF_INET6, address)
        except socket.error:
            return False

        return True

i verified this works on Windows 7, python 2.7.6
